name: Calculator CI

# Trigger
on:
  # When push
  push:
    branches: [ "main" ]

  # When pr
  pull_request:
    branches: [ "main" ]

# Do... 
# job1, job2, ... in Parallel!!
jobs:
  build-and-test:

    # select Virtual OS
    runs-on: ubuntu-latest

    # Steps 
    steps:
      - name: Checkout code

        # Copy to VOS
        uses: actions/checkout@v6

      - name: Set up Node.js

        # install Node.js to VOS
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run Lint
        run: npm run lint

      - name: Run tests
        run: npm test

